access_key_id: "AKIAIOPEJJKQXJXFPRSQ"
secret_access_key: "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"

class User
  has_attached_file :download,
                    :storage => :s3,
                    :s3_credentials => Proc.new{|a| a.instance.s3_credentials }

  def s3_credentials
    {:bucket => "etsydemo", :access_key_id => "AKIAIOPEJJKQXJXFPRSQ", :secret_access_key => "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"}
  end
end
